### ISSUE TITLE
Раздел TODO

### ISSUE THREAD

**Issue by bondiano** [bondiano/pomodoro-todo-bot#2]
Добавить раздел TODO.

- [ ] Возможность добавлять задачу
- [ ] Возможность удалять задачу
- [ ] Возможность назначать задаче количество помодоро-сессий
- [ ] Начать помодоро-сессию с выбранной задачей
- [ ] Список задач
- [ ] Ежедневные напоминания об обзоре списка дел: возможность удалить незавершенные сегодня задачи, перенести их на завтре или если все закончил, то напоминание, что надо добавить новые
